name: Benchmarks
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-cpu=native"
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: llvm-tools-preview, rustfmt, clippy
          
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-bench-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo
            target
            
      - name: Install competitors
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep fd-find grep
          
      - name: Run benchmarks
        run: |
          cargo bench --all-features -- --save-baseline main
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion