name: Benchmarks
on: 
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y hyperfine valgrind strace ripgrep fd-find

      - name: Build project
        run: cargo build --release --all-features
          
      - name: Run benchmarks
        run: |
          mkdir -p results
          chmod +x benches/run.sh
          ./benches/run.sh
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: results/
          
      - name: Compare to main
        run: |
          cargo bench --bench compare -- --baseline main