name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  CARGO_INCREMENTAL: 0  

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, 1.87.0]  # MSRV
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run tests
        run: cargo test --all-features --workspace --verbose

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Check for unused dependencies
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build Release
    needs: [test, lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rfgrep-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rfgrep-windows
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rfgrep-macos
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Generate man page
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p man
          cat > man/rfgrep.1 <<'EOF'
          .TH RFGREP 1 "June 2025" "rfgrep 0.1.0" "User Commands"
          .SH NAME
          rfgrep \- recursive file grep utility
          .SH SYNOPSIS
          rfgrep [OPTIONS] PATTERN [PATH...]
          .SH DESCRIPTION
          rfgrep is a fast, recursive grep tool written in Rust.
          .SH OPTIONS
          .TP
          \-h, \-\-help
          Show help information.
          .TP
          \-v, \-\-version
          Show version information.
          # Add more detailed man page content here...
          EOF
          gzip -f man/rfgrep.1

      - name: Generate completions
        run: |
          mkdir -p completions
          cargo run -- completions bash > completions/rfgrep.bash
          cargo run -- completions zsh > completions/rfgrep.zsh
          cargo run -- completions fish > completions/rfgrep.fish
          cargo run -- completions powershell > completions/rfgrep.ps1
      - name: Create release directory
        run: mkdir -p release
      - name: Copy binary to release directory
        run: cp target/${{ matrix.target }}/release/rfgrep release/
      - name: Prepare additional assets
        run: |
          echo "${{ github.ref_name }}" > release/VERSION
          curl -sSL https://raw.githubusercontent.com/kh3rld/rfgrep/main/LICENSE > release/LICENSE
          mkdir -p examples
          echo "rfgrep search 'pattern' --extensions rs,toml" > examples/usage.txt
      - name: Copy additional files
        run: |
          cp -r examples release/
          cp -r man release/
          cp -r completions release/

      - name: Strip debug symbols (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/rfgrep || true
      
      - name: Package artifacts (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/rfgrep release/
          cp man/rfgrep.1.gz release/ || true
          cp completions/* release/ || true
          cp examples/usage.txt release/ || true
          cp release/VERSION release/
          cp release/LICENSE release/
      
      - name: Package artifacts (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          mkdir release
          Copy-Item "target\${{ matrix.target }}\release\rfgrep.exe" release\
          Copy-Item completions\* release\ -ErrorAction SilentlyContinue
          Copy-Item examples\usage.txt release\ -ErrorAction SilentlyContinue
          Copy-Item release\VERSION release\
          Copy-Item release\LICENSE release\

      - name: Generate checksums (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cd release
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            shasum -a 256 * > SHA256SUMS
          else
            sha256sum * > SHA256SUMS
          fi

      - name: Generate checksums (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd release
          certutil -hashfile rfgrep.exe SHA256 > rfgrep.exe.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: release/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Prepare release assets
        run: |
          mkdir -p dist
          # Organize by platform
          for artifact in artifacts/*; do
            platform=$(basename $artifact | sed 's/rfgrep-//')
            mkdir -p dist/$platform
            cp $artifact/* dist/$platform/
          done
          
          # Combine checksums
          find artifacts -name "SHA256SUMS" -exec cat {} \; > dist/SHA256SUMS
          find artifacts -name "*.sha256" -exec cat {} \; > dist/SHA256SUMS.windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          discussion_category_name: "Announcements"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to Crates.io
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Publish to crates.io
        run: |
          cargo publish --dry-run --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
